In [1]:
!pip install numpy

In [1]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
arr2 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr2)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [3]:
print(arr2[0][1][1])

5


In [4]:
print(arr2[1][1][1])

5


In [5]:
print(arr2[1][0][1])

2


In [6]:
arr= np.array([1,2,3,4,5,6,7,8])

In [7]:
print(arr[3:])

[4 5 6 7 8]


In [9]:
print(arr[-3:])
import numpy as np
arr = np.array([True,False,True],dtype='s')
print(arr.dtype)
arr2 = np.astype(bool)
print(arr2.dtype)

[6 7 8]


TypeError: data type 's' not understood